### ISSUE TITLE
workaround included: rqt won't load cpp plugins due to SIP not loading even though Shiboken/PySide should be used

### ISSUE THREAD

**Issue by Pleune** [lopsided98/nix-ros-overlay#404]
It seem like qt_qui_cpp is keeping rqt_image_view from loading into the rqt plugins list. It looks like after d3c90ec, Pyside/Shiboken should be used instead of PyQt/SIP,  but python_qt_binding is still preferring SIP.  Interestingly, when running plugins directly, they seem to work. For example `ros2 run rqt_image_view rqt_image_view`, instead of trying to add it to `rqt`.

**Error when running `rqt`**
```
Could not import "pyqt" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/nix/store/hyf3pk2c0cglgfzb064nlxg76ldn6zwx-ros-env/lib/python3.11/site-packages/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    from . import libqt_gui_cpp_sip
ImportError: cannot import name 'libqt_gui_cpp_sip' from 'qt_gui_cpp' (/nix/store/hyf3pk2c0cglgfzb064nlxg76ldn6zwx-ros-env/lib/python3.11/site-packages/qt_gui_cpp/__init__.py)
```

Which shows that QT_BINDING is being chosen as pyqt. But as libqt_gui_cpp_sip is not in the qt_qui_cpp folder, due to the linked commit. Reverting that commit does not help, because SIP still is broken and does not compile. I have not investigated trying to fix that compile issue.

**/nix/store/hyf3pk2c0cglgfzb064nlxg76ldn6zwx-ros-env/lib/python3.11/site-packages/qt_gui_cpp/cpp_binding_helper.py:**
```
  33   │ from python_qt_binding import QT_BINDING
  34   │ from python_qt_binding.QtCore import qWarning
  35   │
  36   │
  37   │ try:
  38   │     if QT_BINDING == 'pyside':
  39   │         from . import libqt_gui_cpp_shiboken
  40   │         qt_gui_cpp = libqt_gui_cpp_shiboken.qt_gui_cpp
  41   │
  42   │     elif QT_BINDING == 'pyqt':
  43   │         from . import libqt_gui_cpp_sip
  44   │         qt_gui_cpp = libqt_gui_cpp_sip.qt_gui_cpp
  45   │
  46   │     else:
  47   │         raise ImportError('Qt binding name "%s" is unknown.' % QT_BINDING)
```

I also expect that this is not an issue on darwin, because on darwin SIP is not preferred by python_qt_bindings

**/nix/store/hyf3pk2c0cglgfzb064nlxg76ldn6zwx-ros-env/lib/python3.11/site-packages/python_qt_binding/binding_helper.py:**
```
  50   │ def _select_qt_binding(binding_name=None, binding_order=None):
  51   │     global QT_BINDING, QT_BINDING_VERSION
  52   │
  53   │     # order of default bindings can be changed here
  54   │     if platform.system() == 'Darwin':
  55   │         DEFAULT_BINDING_ORDER = ['pyside']
  56   │     else:
  57   │         DEFAULT_BINDING_ORDER = ['pyqt', 'pyside']
  58   │
  59   │     binding_order = binding_order or DEFAULT_BINDING_ORDER
```

The way python_qt_binding is written, pyqt will always be chosen on non-Darwin, unless the `SELECT_QT_BINDING` or `SELECT_QT_BINDING_ORDER` attrs are set on sys to `pyside`.  

Now, what I have done, is just patched python-qt-bindings to never check for pyqt:

**Overlay:**
```
python-qt-binding = rosSuper.python-qt-binding.overrideAttrs (
  {
    patches ? [ ],
    propagatedBuildInputs ? [ ],
    ...
  }:
  {
    patches = patches ++ [ ./python_qt_binding.patch ];
    propagatedBuildInputs =
      propagatedBuildInputs
      ++ (with rosSelf.pythonPackages; [
        shiboken2
        pyside2
      ]);
  }
);
```

with

**./python_qt_binding.patch**
```
diff -rBNu a/src/python_qt_binding/binding_helper.py b/src/python_qt_binding/binding_helper.py
--- a/src/python_qt_binding/binding_helper.py   2024-05-02 11:03:48.047406945 -0400
+++ b/src/python_qt_binding/binding_helper.py   2024-05-02 11:04:19.445777970 -0400
@@ -51,10 +51,7 @@
     global QT_BINDING, QT_BINDING_VERSION

     # order of default bindings can be changed here
-    if platform.system() == 'Darwin':
-        DEFAULT_BINDING_ORDER = ['pyside']
-    else:
-        DEFAULT_BINDING_ORDER = ['pyqt', 'pyside']
+    DEFAULT_BINDING_ORDER = ['pyside']

     binding_order = binding_order or DEFAULT_BINDING_ORDER
```

And this works! The image_view plugin loads (and other cpp plugins also fixed)

![image](https://github.com/lopsided98/nix-ros-overlay/assets/9004509/63394743-aee2-475d-b1d4-2af4a018bc18)

I would recommend adding this patch as a supplement to d3c90ec, using PySide in all situations. But, admittedly, I am not 100% confident that this does not mess anything else up.

Now, I don't know why the icons are broken... but they still work when you click them.

**Comment by Pleune** [comment]
This seems like a more proper fix. but I do think it would be good to keep the pyside build inputs included as well, because in theory consumers of python-qt-bindings could ask for one or the other implementation. Does including them cause any issues? Additionally, this would also not work with ros humble on darwin, since python-qt-bindings' release for humble removes pyqt as an option (see my snippet above).

I would love to submit a PR with these changes if nobody else can, but I will be a few weeks before I have time to do a quick test on each distro.
